# Generated by Django 2.1.4 on 2019-01-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100, unique=True)),
                ('shops', models.TextField()),
                ('brands', models.TextField()),
                ('productURL', models.URLField(unique=True, verbose_name='URL du produit')),
                ('nutriscore', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Produit',
                'ordering': ['productName'],
            },
        ),
    ]
