# Generated by Django 2.1.4 on 2019-02-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0003_auto_20190204_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='flo@flo.com', max_length=254),
            preserve_default=False,
        ),
    ]
