# Generated by Django 2.1.4 on 2019-02-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0006_auto_20190205_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
