# Generated by Django 2.1.4 on 2019-02-06 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0008_auto_20190206_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['product'], 'verbose_name': 'Favoris', 'verbose_name_plural': 'Favoris'},
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='productID',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='substitueID',
        ),
        migrations.AddField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_product', to='webSite.Product'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='substitute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_substitute', to='webSite.Product'),
        ),
    ]
